version: '3.9'

services:
  api:
    build: .
    restart: on-failure
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    restart: on-failure
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env